CREATE DATABASE cows;

USE cows;

CREATE TABLE cows (
  cowId INTEGER(250) AUTO_INCREMENT,
  cowName VARCHAR(250) NULL DEFAULT NULL,
  cowDescr VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (cowId)
);